/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazGrafica;

import java.lang.String;
import javax.swing.table.DefaultTableModel;
import dominio.SistemaOperativo;
import java.util.Observable;
import javax.swing.JOptionPane;

/**
 *
 * @author nicol
 */

public class inicioSesion extends javax.swing.JFrame implements Runnable {

    private SistemaOperativo sis;
    
    public inicioSesion() {
        initComponents();
    }

    public inicioSesion(SistemaOperativo sistema) {
             initComponents();
             ocultarPasw();
             sis=sistema;
           
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEleccionUsuario = new javax.swing.JPanel();
        bSuperU = new javax.swing.JButton();
        bUsuario = new javax.swing.JButton();
        bInvitado = new javax.swing.JButton();
        bVolver = new javax.swing.JButton();
        bApagar = new javax.swing.JButton();
        txtpasword = new javax.swing.JTextField();
        textPasw = new javax.swing.JLabel();
        bIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bSuperU.setText("superUsuario");
        bSuperU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSuperUActionPerformed(evt);
            }
        });

        bUsuario.setText("usuario");
        bUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUsuarioActionPerformed(evt);
            }
        });

        bInvitado.setText("Invitado");
        bInvitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInvitadoActionPerformed(evt);
            }
        });

        bVolver.setText("Volver");
        bVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverActionPerformed(evt);
            }
        });

        bApagar.setText("apagar");

        txtpasword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpasword.setText("pasword");
        txtpasword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpaswordActionPerformed(evt);
            }
        });

        textPasw.setText("pasword");

        bIngresar.setText("ingresar");
        bIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEleccionUsuarioLayout = new javax.swing.GroupLayout(panelEleccionUsuario);
        panelEleccionUsuario.setLayout(panelEleccionUsuarioLayout);
        panelEleccionUsuarioLayout.setHorizontalGroup(
            panelEleccionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEleccionUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelEleccionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bApagar, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addGap(23, 23, 23))
            .addGroup(panelEleccionUsuarioLayout.createSequentialGroup()
                .addGroup(panelEleccionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEleccionUsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bSuperU, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(bUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bInvitado, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEleccionUsuarioLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(txtpasword, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEleccionUsuarioLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(textPasw, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        panelEleccionUsuarioLayout.setVerticalGroup(
            panelEleccionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEleccionUsuarioLayout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(textPasw)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEleccionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpasword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bIngresar))
                .addGap(18, 18, 18)
                .addGroup(panelEleccionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSuperU)
                    .addComponent(bUsuario)
                    .addComponent(bInvitado))
                .addGap(18, 18, 18)
                .addComponent(bVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bApagar)
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEleccionUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEleccionUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUsuarioActionPerformed
        mostrarPanelContrasena( bUsuario.getText());
    }//GEN-LAST:event_bUsuarioActionPerformed

    private void bSuperUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSuperUActionPerformed
        mostrarPanelContrasena( bSuperU.getText());
    }//GEN-LAST:event_bSuperUActionPerformed

    private void bInvitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInvitadoActionPerformed
        this.setVisible(false);
       Escritorio esc= new Escritorio(sis, "invitado") {
            @Override
            public void update(Observable arg0, Object arg1) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        };
       esc.setVisible(true);
    }//GEN-LAST:event_bInvitadoActionPerformed

    private void bVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverActionPerformed
        ocultarPasw();
        mostrarPanelEleccion();
    }//GEN-LAST:event_bVolverActionPerformed

    private void txtpaswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpaswordActionPerformed
      
    }//GEN-LAST:event_txtpaswordActionPerformed

    private void bIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIngresarActionPerformed
       boolean valido=sis.usuarioValido(txtpasword.getText(),textPasw.getText());
       if(valido){
          this.setVisible(false);
          Escritorio esc=new Escritorio(sis,textPasw.getText()) {
              @Override
              public void update(Observable arg0, Object arg1) {
                  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
              }
          };
          esc.setVisible(true);
       }else{
           JOptionPane.showMessageDialog(this, "ingrese de nuevo la constrasena", "Error", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_bIngresarActionPerformed

  void  ocultarPasw(){
        bIngresar.setVisible(false);
        textPasw.setVisible(false);
        txtpasword.setVisible(false);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicioSesion().setVisible(true);
            }
        });
    }

    public void hola(){
        
    }
    
  private void  mostrarPanelContrasena(String tipoU){
      bSuperU.setVisible(false);
      bUsuario.setVisible(false);
      bInvitado.setVisible(false);
      bVolver.setVisible(true);
      txtpasword.setVisible(true);
      textPasw.setText(tipoU);
      textPasw.setVisible(true);
      bIngresar.setVisible(true);
    }
  private void mostrarPanelEleccion(){
      bSuperU.setVisible(true);
      bUsuario.setVisible(true);
      bInvitado.setVisible(true);
      txtpasword.setVisible(false);
      textPasw.setVisible(false);
  }
  
  private void ocultarPanelEleccion(){
     
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bApagar;
    private javax.swing.JButton bIngresar;
    private javax.swing.JButton bInvitado;
    private javax.swing.JButton bSuperU;
    private javax.swing.JButton bUsuario;
    private javax.swing.JButton bVolver;
    private javax.swing.JPanel panelEleccionUsuario;
    private javax.swing.JLabel textPasw;
    private javax.swing.JTextField txtpasword;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
    this.setVisible(true);
    }
}
